name: test

on:
  workflow_call:

jobs:
  run:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      fail-fast: true
      matrix:
        go: ['stable', 'oldstable']

    steps:
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
          check-latest: true

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run tests
        run: go test -v -count=1 -race -shuffle=on -coverprofile=coverage.txt ./...

      - name: Upload Coverage
        uses: codecov/codecov-action@v3
        continue-on-error: true
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./coverage.txt
          fail_ci_if_error: false
